apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: w8fm808nu-python-gitops
  description: This is GitOps manifest for w8fm808nu-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=w8fm808nu-python
    backstage.io/kubernetes-id: w8fm808nu-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: w8fm808nu-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:w8fm808nu-python
