apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w8fm808nu-python
  janus-idp.io/tekton: w8fm808nu-python
  backstage.io/kubernetes-id: w8fm808nu-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: w8fm808nu-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
